baseURL: "https://syedzayyan.com/"
title: Existential with Zayyan
paginate: 5
theme: PaperMod
publishDir: "docs"
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About
                  url: about/
                  weight: 1
                - name: Search
                  url: search/
                  weight: 2
                - name: Tags
                  url: tags/
                  weight: 3

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: I write stuff
    author: Syed Zayyan Masud
    # author: ["Me", "You"] # multiple authors
    comments: true
    defaultTheme: dark
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    images: ["profile_pic.jpg"]

    profileMode:
        enabled: false
        title: Syed Zayyan Masud
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hello! I am Zayyan 👋"
        Content: >
            I write things when I feel like it, and this blog is just for that.


            As of 2022 I am still at University, getting a degree in Pharmacology at QMUL


            I sing and play guitar and sometimes put out original music.


            Sometimes I code in JS, Python and Go (to mantain this blog). 😊
    socialIcons:
        - name: github
          url: "https://github.com/syedzayyan/"
        - name: linkedin
          url: "https://www.linkedin.com/in/zayyan-masud-5988ba19b/"
        - name: instagram
          url: "https://instagram.com/syed._.zayyan"
        - name: youtube
          url: "https://youtube.com/c/ZayyanMasud"
        - name: spotify
          url: "https://open.spotify.com/artist/2ooLo1eEuSgsSKhUqBArHr"   
        - name: RsS
          url: "index.xml"    

    editPost:
        URL: "https://github.com/syedzayyan/syedzayyan.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link
    staticman_api: "https://commentz.herokuapp.com/v2/entry/syedzayyan/syedzayyan.github.io/main/comments"

    assets:
         favicon: "/favicon.ico"
         favicon16x16: "/favicon.ico"
         favicon32x32: "/favicon.ico"
         apple_touch_icon: "/favicon.ico"
         safari_pinned_tab: "/favicon.ico"


taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
